apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-monitor-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-monitor-reader
rules:
- apiGroups: [""]
  resources: ["pods", "events", "logs"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-monitor-binding
subjects:
- kind: ServiceAccount
  name: ai-monitor-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ai-monitor-reader
  apiGroup: rbac.authorization.k8s.io